#!/usr/bin/env sh
#
# Update docker image on docker hub including new app version
#

if [ "${NOLOCK:-}" != true ] && [ "${FLOCKER:-}" != "$0" ]; then
  exec env FLOCKER="$0" flock -E 3 -en "$0" sh "$0" "$@" || :
fi

set -eu

# shellcheck disable=SC1007
cd "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"

find . -type f -name Dockerfile |
  while read -r file; do
    (
      echo "# In ${file%/*}"
      sh "${file%/*}/deliver" || :
    )
  done
